### ISSUE TITLE
email written wrong by the bot

### ISSUE THREAD

**Issue by dragdr** [farshadz1997/Microsoft-Rewards-bot#327]
When i start the bot it has some problems loging in into some of the accounts, even if the emails are written correctly in the "accounts" file. The bot adds some symbols like "$" that are not there in " accounts ". I tried to rewrite the emails but i still have this issue.
Example: **â€Ž**asciugpalank@ is what i see in the terminal,
x.com **\u00e2\u20ac\u017d** " this is what i see in "Logs_accoounts" 
(I copied only part of the email not the full email, I evidentiated the parts added by the bot)

**Comment by AkhilProto** [comment]
It seems like the issue is related to **encoding**. The symbols you are seeing in the terminal and in the logs suggest that there might be some problem with the encoding used to read the email addresses from the accounts file.

One possible solution could be to **check the encoding of the accounts file** and make sure it is in the correct format. It's possible that the file is saved in a different encoding than what your program is expecting.

Another thing to check is the encoding settings of your terminal. If your terminal is not set to display the correct encoding, it could be displaying the symbols incorrectly.

**Comment by dragdr** [comment]
I solved it. It was a problem doe to the copy paste i did while writting accounts. I rerwitted it by hand and now it works.
